[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Remappings
remappings = [
    "@uniswap/v4-core/=lib/v4-core/",
    "@uniswap/v4-periphery/=lib/v4-periphery/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "solmate/src/=lib/solmate/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
